"""Initial schema: all ORM tables (single head).

Revision ID: initial
Revises:
Create Date: 2026-05-09
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dashboard_magic_links",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "ix_dashboard_magic_links_email_created_at",
        "dashboard_magic_links",
        ["email", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_dashboard_magic_links_expires_at", "dashboard_magic_links", ["expires_at"], unique=False
    )
    op.create_table(
        "dashboard_users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("idp_provider", sa.String(length=64), nullable=True),
        sa.Column("idp_subject", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dashboard_users_email"), "dashboard_users", ["email"], unique=True)
    op.create_table(
        "ingest_aggregate_dead_letters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("replayed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingest_agg_dl_created", "ingest_aggregate_dead_letters", ["created_at"], unique=False
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scheduler_job_leases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.String(length=64), nullable=False),
        sa.Column("owner_token", sa.String(length=64), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_scheduler_job_leases_expires_at",
        "scheduler_job_leases",
        ["lease_expires_at"],
        unique=False,
    )
    op.create_index(
        "ux_scheduler_job_leases_job_name", "scheduler_job_leases", ["job_name"], unique=True
    )
    op.create_table(
        "governance_audit_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=64), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["dashboard_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_governance_audit_org_created_at",
        "governance_audit_events",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "organization_memberships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("invited_email", sa.String(length=320), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["dashboard_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_org_memberships_org_user",
        "organization_memberships",
        ["organization_id", "user_id"],
        unique=True,
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "onboarding_completed", sa.Boolean(), server_default=sa.text("0"), nullable=False
        ),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projects_organization_id"), "projects", ["organization_id"], unique=False
    )
    op.create_table(
        "alert_dispatches",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("alert_type", sa.String(length=32), nullable=False),
        sa.Column("destination_email", sa.String(length=320), nullable=True),
        sa.Column("delivered_via", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_alert_dispatches_project_triggered_at",
        "alert_dispatches",
        ["project_id", "triggered_at"],
        unique=False,
    )
    op.create_index(
        "ix_alert_dispatches_project_type_triggered_at",
        "alert_dispatches",
        ["project_id", "alert_type", "triggered_at"],
        unique=False,
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("key_id", sa.String(length=32), nullable=False),
        sa.Column("key_salt", sa.LargeBinary(), nullable=False),
        sa.Column("key_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_id"), "api_keys", ["key_id"], unique=True)
    op.create_table(
        "archived_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("original_event_id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_archived_events_original_event_id",
        "archived_events",
        ["original_event_id"],
        unique=False,
    )
    op.create_index(
        "ix_archived_events_project_archived_at",
        "archived_events",
        ["project_id", "archived_at"],
        unique=False,
    )
    op.create_table(
        "dashboard_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["organization_id"], ["organizations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["dashboard_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(
        "ix_dashboard_sessions_expires_at", "dashboard_sessions", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_dashboard_sessions_user_created_at",
        "dashboard_sessions",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "dashboard_user_bookmarks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("pathname", sa.String(length=512), nullable=False),
        sa.Column("query_string", sa.Text(), nullable=True),
        sa.Column("hash_fragment", sa.String(length=2048), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["dashboard_users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dashboard_user_bookmarks_user_project_updated",
        "dashboard_user_bookmarks",
        ["user_id", "project_id", "updated_at"],
        unique=False,
    )
    op.create_table(
        "dashboard_widget_definitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("widget_id", sa.String(length=128), nullable=False),
        sa.Column("widget_type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dashboard_widget_definitions_project_order",
        "dashboard_widget_definitions",
        ["project_id", "display_order"],
        unique=False,
    )
    op.create_index(
        "ux_dashboard_widget_definitions_project_widget_id",
        "dashboard_widget_definitions",
        ["project_id", "widget_id"],
        unique=True,
    )
    op.create_table(
        "dashboard_widget_points",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("widget_id", sa.String(length=128), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_dashboard_widget_points_project_timestamp",
        "dashboard_widget_points",
        ["project_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_dashboard_widget_points_project_widget_id",
        "dashboard_widget_points",
        ["project_id", "widget_id"],
        unique=False,
    )
    op.create_table(
        "error_group_aggregates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("group_key", sa.String(length=255), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("exception_type", sa.String(length=255), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("sample_stack_trace", sa.Text(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_error_group_aggregates_project_last_seen",
        "error_group_aggregates",
        ["project_id", "last_seen"],
        unique=False,
    )
    op.create_index(
        "ux_error_group_aggregates_project_group_key",
        "error_group_aggregates",
        ["project_id", "group_key"],
        unique=True,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sdk_version", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("environment", sa.String(length=128), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_events_project_path_timestamp_desc",
        "events",
        ["project_id", "path", "timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_events_project_timestamp_desc", "events", ["project_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_events_project_type_timestamp_desc",
        "events",
        ["project_id", "type", "timestamp"],
        unique=False,
    )
    op.create_table(
        "ingest_idempotency_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("accepted_events", sa.Integer(), nullable=True),
        sa.Column(
            "reserved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "key_hash", name="ux_ingest_idempotency_project_key"),
    )
    op.create_index(
        "ix_ingest_idempotency_project_reserved",
        "ingest_idempotency_keys",
        ["project_id", "reserved_at"],
        unique=False,
    )
    op.create_table(
        "ingest_rate_limit_windows",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingest_rate_limit_windows_window_start",
        "ingest_rate_limit_windows",
        ["window_start"],
        unique=False,
    )
    op.create_index(
        "ux_ingest_rate_limit_windows_project_window",
        "ingest_rate_limit_windows",
        ["project_id", "window_start"],
        unique=True,
    )
    op.create_table(
        "ingest_sql_tail_repair_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_retry_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dead_lettered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingest_sql_tail_repair_pending",
        "ingest_sql_tail_repair_items",
        ["resolved_at", "dead_lettered_at", "next_retry_at"],
        unique=False,
    )
    op.create_index(
        "ix_ingest_sql_tail_repair_project_created",
        "ingest_sql_tail_repair_items",
        ["project_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "metric_buckets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("minute_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("environment", sa.String(length=128), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("latency_total_ms", sa.Float(), nullable=False),
        sa.Column("count_2xx", sa.Integer(), nullable=False),
        sa.Column("count_3xx", sa.Integer(), nullable=False),
        sa.Column("count_4xx", sa.Integer(), nullable=False),
        sa.Column("count_5xx", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_metric_buckets_project_minute",
        "metric_buckets",
        ["project_id", "minute_start"],
        unique=False,
    )
    op.create_index(
        "ux_metric_buckets_project_minute_service_env",
        "metric_buckets",
        ["project_id", "minute_start", "service_name", "environment"],
        unique=True,
    )
    op.create_table(
        "project_alert_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("destination_email", sa.String(length=320), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("slack_enabled", sa.Boolean(), nullable=False),
        sa.Column("slack_webhook_url", sa.String(length=2048), nullable=True),
        sa.Column("discord_enabled", sa.Boolean(), nullable=False),
        sa.Column("discord_webhook_url", sa.String(length=2048), nullable=True),
        sa.Column("webhook_enabled", sa.Boolean(), nullable=False),
        sa.Column("webhook_url", sa.String(length=2048), nullable=True),
        sa.Column("error_spike_ratio_threshold", sa.Float(), nullable=False),
        sa.Column("error_spike_min_requests", sa.Integer(), nullable=False),
        sa.Column("error_spike_window_minutes", sa.Integer(), nullable=False),
        sa.Column("outage_min_requests", sa.Integer(), nullable=False),
        sa.Column("outage_window_minutes", sa.Integer(), nullable=False),
        sa.Column("cooldown_minutes", sa.Integer(), nullable=False),
        sa.Column("last_error_spike_alert_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_outage_alert_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    op.create_table(
        "project_ui_settings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("theme_preference", sa.String(length=16), nullable=False),
        sa.Column("exclude_lumonox_traffic", sa.Boolean(), nullable=False),
        sa.Column("event_plane_use_snapshot_read", sa.Boolean(), nullable=False),
        sa.Column("retention_raw_events_days", sa.Integer(), nullable=True),
        sa.Column("retention_max_db_size_mb", sa.Integer(), nullable=True),
        sa.Column("retention_max_log_rows", sa.Integer(), nullable=True),
        sa.Column("retention_plan", sa.String(length=32), nullable=False),
        sa.Column("archival_enabled", sa.Boolean(), nullable=False),
        sa.Column("archival_mode", sa.String(length=32), nullable=False),
        sa.Column("archival_status", sa.String(length=16), nullable=False),
        sa.Column("archival_last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archival_last_error", sa.Text(), nullable=True),
        sa.Column("logs_query_max_window_minutes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_ui_settings")
    op.drop_table("project_alert_settings")
    op.drop_index("ux_metric_buckets_project_minute_service_env", table_name="metric_buckets")
    op.drop_index("ix_metric_buckets_project_minute", table_name="metric_buckets")
    op.drop_table("metric_buckets")
    op.drop_index(
        "ix_ingest_sql_tail_repair_project_created", table_name="ingest_sql_tail_repair_items"
    )
    op.drop_index("ix_ingest_sql_tail_repair_pending", table_name="ingest_sql_tail_repair_items")
    op.drop_table("ingest_sql_tail_repair_items")
    op.drop_index(
        "ux_ingest_rate_limit_windows_project_window", table_name="ingest_rate_limit_windows"
    )
    op.drop_index(
        "ix_ingest_rate_limit_windows_window_start", table_name="ingest_rate_limit_windows"
    )
    op.drop_table("ingest_rate_limit_windows")
    op.drop_index("ix_ingest_idempotency_project_reserved", table_name="ingest_idempotency_keys")
    op.drop_table("ingest_idempotency_keys")
    op.drop_index("ix_events_project_type_timestamp_desc", table_name="events")
    op.drop_index("ix_events_project_timestamp_desc", table_name="events")
    op.drop_index("ix_events_project_path_timestamp_desc", table_name="events")
    op.drop_table("events")
    op.drop_index(
        "ux_error_group_aggregates_project_group_key", table_name="error_group_aggregates"
    )
    op.drop_index(
        "ix_error_group_aggregates_project_last_seen", table_name="error_group_aggregates"
    )
    op.drop_table("error_group_aggregates")
    op.drop_index(
        "ix_dashboard_widget_points_project_widget_id", table_name="dashboard_widget_points"
    )
    op.drop_index(
        "ix_dashboard_widget_points_project_timestamp", table_name="dashboard_widget_points"
    )
    op.drop_table("dashboard_widget_points")
    op.drop_index(
        "ux_dashboard_widget_definitions_project_widget_id",
        table_name="dashboard_widget_definitions",
    )
    op.drop_index(
        "ix_dashboard_widget_definitions_project_order", table_name="dashboard_widget_definitions"
    )
    op.drop_table("dashboard_widget_definitions")
    op.drop_index(
        "ix_dashboard_user_bookmarks_user_project_updated", table_name="dashboard_user_bookmarks"
    )
    op.drop_table("dashboard_user_bookmarks")
    op.drop_index("ix_dashboard_sessions_user_created_at", table_name="dashboard_sessions")
    op.drop_index("ix_dashboard_sessions_expires_at", table_name="dashboard_sessions")
    op.drop_table("dashboard_sessions")
    op.drop_index("ix_archived_events_project_archived_at", table_name="archived_events")
    op.drop_index("ix_archived_events_original_event_id", table_name="archived_events")
    op.drop_table("archived_events")
    op.drop_index(op.f("ix_api_keys_key_id"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index("ix_alert_dispatches_project_type_triggered_at", table_name="alert_dispatches")
    op.drop_index("ix_alert_dispatches_project_triggered_at", table_name="alert_dispatches")
    op.drop_table("alert_dispatches")
    op.drop_index(op.f("ix_projects_organization_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index("ix_org_memberships_org_user", table_name="organization_memberships")
    op.drop_table("organization_memberships")
    op.drop_index("ix_governance_audit_org_created_at", table_name="governance_audit_events")
    op.drop_table("governance_audit_events")
    op.drop_index("ux_scheduler_job_leases_job_name", table_name="scheduler_job_leases")
    op.drop_index("ix_scheduler_job_leases_expires_at", table_name="scheduler_job_leases")
    op.drop_table("scheduler_job_leases")
    op.drop_table("organizations")
    op.drop_index("ix_ingest_agg_dl_created", table_name="ingest_aggregate_dead_letters")
    op.drop_table("ingest_aggregate_dead_letters")
    op.drop_index(op.f("ix_dashboard_users_email"), table_name="dashboard_users")
    op.drop_table("dashboard_users")
    op.drop_index("ix_dashboard_magic_links_expires_at", table_name="dashboard_magic_links")
    op.drop_index("ix_dashboard_magic_links_email_created_at", table_name="dashboard_magic_links")
    op.drop_table("dashboard_magic_links")
    # ### end Alembic commands ###
