/**
 * Central lucide-react re-exports for tree-shaking and consistent icon imports.
 */
export type { LucideIcon } from "lucide-react";

export {
  Activity,
  Ban,
  Bell,
  Bookmark,
  CalendarClock,
  Check,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  ClipboardList,
  ExternalLink,
  FilterX,
  History,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  ListChecks,
  LogOut,
  MoreVertical,
  Pencil,
  Plus,
  PanelLeft,
  PanelLeftClose,
  Pause,
  Play,
  Rocket,
  RotateCw,
  ScrollText,
  Settings,
  Share2,
  SlidersHorizontal,
  Sparkles,
  Stethoscope,
  Trash2,
  Undo2,
  X,
} from "lucide-react";
